[package]
name = "diesel_full_text_search"
version = "1.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
description = "Adds support for PostgreSQL full text search to Diesel"
license = "MIT"
repository = "https://github.com/diesel-rs/diesel_full_text_search"

[dependencies]
diesel = { version = "1.4", features = ["postgres"] }
